//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JB007.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        public long Id { get; set; }
        public System.Guid TenantId { get; set; }
        public string UserName { get; set; }
        public Nullable<long> LoginId { get; set; }
        public string PhoneNumber { get; set; }
        public string TimeZone { get; set; }
        public bool IsActive { get; set; }
        public string UserEmail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Password { get; set; }
    }
}
